name: test_for_new_work
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  flutter_bloc: ^8.1.6
  json_annotation: ^4.8.1

dev_dependencies:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
